# Generated by Django 5.2.8 on 2026-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='division',
            field=models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C'), ('D', 'Division D')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time_slot',
            field=models.CharField(choices=[('9-10', '9-10'), ('10-11', '10-11'), ('11:15-12:15', '11:15-12:15'), ('12:15-1:15', '12:15-1:15'), ('3-4', '3-4')], max_length=20),
        ),
    ]
